#%RAML 1.0
title: Hello
mediaType: application/json
baseUri: http://hello.org
uses:
 c: ../../collections.raml
types:
  Item:
    properties:
      id: integer
      name: string
/items:
   get:
     (c.paging):
       page: page
       limit: limit
     queryParameters:
       page: number
       limit?:  number
       filter?: string
     responses:
       200:
         body: Item[]