#%RAML 1.0
title: Hello
mediaType: application/json
baseUri: http://hello.org
uses:
 c: ../../collections.raml
types:
  Item:
    properties:
      id: integer
      name: string
/items:
   get:
     queryParameters:
       offset: number
     (c.paging):
       result: items
       total: total
       offset: offset
     responses:
       200:
         body:
           properties:
             items:
               items: Item
               type: array
             total: number